export const assets = [
  {
    id: "customer-story",
    name: "Customer story — Acme",
    fileName: "acme_interview_final_v3.mp4",
    status: "ready",
    mediaType: "video",
    duration: "18:42",
    source: "Google Drive",
    uploadedAt: "Today, 9:42 AM",
    moments: 12,
    size: "2.4 GB",
    visual: "portrait",
    colors: ["#d7c4b4", "#5d4437"],
    description: "Customer interview on onboarding, implementation, and early wins.",
  },
  {
    id: "founder-notes",
    name: "Founder notes — July",
    fileName: "IMG_4831.MOV",
    status: "processing",
    mediaType: "video",
    duration: "08:16",
    source: "Direct upload",
    uploadedAt: "Today, 8:17 AM",
    moments: 0,
    size: "849 MB",
    visual: "window",
    colors: ["#8aa3a1", "#233e43"],
    description: "A casual founder recording with product positioning ideas.",
  },
  {
    id: "product-demo",
    name: "Platform walkthrough",
    fileName: "mediaflow_demo_02.mp4",
    status: "ready",
    mediaType: "video",
    duration: "12:04",
    source: "Direct upload",
    uploadedAt: "Yesterday",
    moments: 18,
    size: "1.2 GB",
    visual: "screen",
    colors: ["#c9dfda", "#2d645c"],
    description: "Full product demonstration covering search, collections, and export.",
  },
  {
    id: "team-offsite",
    name: "Team offsite recap",
    fileName: "offsite_recap_2025.mp4",
    status: "ready",
    mediaType: "video",
    duration: "04:38",
    source: "Google Drive",
    uploadedAt: "Jul 22, 2026",
    moments: 7,
    size: "628 MB",
    visual: "landscape",
    colors: ["#d8c9a4", "#53663f"],
    description: "Fast-moving team footage with culture and behind-the-scenes moments.",
  },
  {
    id: "webinar",
    name: "Growth systems webinar",
    fileName: "webinar_master.mp4",
    status: "failed",
    mediaType: "video",
    duration: "46:20",
    source: "Google Drive",
    uploadedAt: "Jul 20, 2026",
    moments: 0,
    size: "4.1 GB",
    visual: "stage",
    colors: ["#cbbecf", "#4a3553"],
    description: "A long-form conversation about repeatable marketing operations.",
  },
  {
    id: "product-stills",
    name: "Product stills — Summer",
    fileName: "summer_product_selects",
    status: "ready",
    mediaType: "image",
    duration: "24 files",
    source: "Direct upload",
    uploadedAt: "Jul 18, 2026",
    moments: 24,
    size: "186 MB",
    visual: "object",
    colors: ["#e3d4bc", "#8f4d34"],
    description: "Warm product photography approved for evergreen campaigns.",
  },
];

export const transcript = [
  {
    startMs: 0,
    time: "00:00",
    speaker: "Interviewer",
    text: "Tell me what implementation looked like before you started.",
  },
  {
    startMs: 14_000,
    time: "00:14",
    speaker: "Maya",
    text: "We assumed it would take several weeks and involve our entire operations team.",
  },
  {
    startMs: 31_000,
    time: "00:31",
    speaker: "Maya",
    text: "The surprise was how easy onboarding felt. We connected our library on a Tuesday.",
  },
  {
    startMs: 48_000,
    time: "00:48",
    speaker: "Maya",
    text: "By Thursday, the team was finding customer moments we had completely forgotten.",
  },
  {
    startMs: 67_000,
    time: "01:07",
    speaker: "Interviewer",
    text: "What changed for the way your marketing team works?",
  },
  {
    startMs: 78_000,
    time: "01:18",
    speaker: "Maya",
    text: "We stopped asking where the footage was and started asking what story we wanted to tell.",
  },
];

export const moments = [
  {
    id: "moment-1",
    title: "Onboarding was easier than expected",
    time: "00:31–00:53",
    startMs: 31_000,
    type: "Testimonial",
    score: 96,
  },
  {
    id: "moment-2",
    title: "From forgotten footage to useful stories",
    time: "00:48–01:04",
    startMs: 48_000,
    type: "Outcome",
    score: 92,
  },
  {
    id: "moment-3",
    title: "A better question for the marketing team",
    time: "01:18–01:34",
    startMs: 78_000,
    type: "Brand story",
    score: 89,
  },
];

export const searchResults = [
  {
    id: "result-1",
    assetId: "customer-story",
    title: "Onboarding was easier than expected",
    assetName: "Customer story — Acme",
    timestamp: "00:31",
    excerpt:
      "The surprise was how easy onboarding felt. We connected our library on a Tuesday.",
    reason: "Direct speech about easy onboarding in a customer testimonial.",
    score: 0.96,
    colors: ["#d7c4b4", "#5d4437"],
  },
  {
    id: "result-2",
    assetId: "product-demo",
    title: "Connect a library in minutes",
    assetName: "Platform walkthrough",
    timestamp: "02:14",
    excerpt:
      "Choose a folder, confirm the organization, and MediaFlow begins cataloguing every file.",
    reason: "Product demonstration visually shows the onboarding workflow.",
    score: 0.88,
    colors: ["#c9dfda", "#2d645c"],
  },
  {
    id: "result-3",
    assetId: "founder-notes",
    title: "Make the first useful result immediate",
    assetName: "Founder notes — July",
    timestamp: "04:08",
    excerpt:
      "People should understand the value before they finish setting everything up.",
    reason: "Conceptual match about reducing time-to-value during onboarding.",
    score: 0.81,
    colors: ["#8aa3a1", "#233e43"],
  },
];

export const collections = [
  {
    id: "launch-campaign",
    name: "Launch campaign",
    description: "Proof points, customer wins, and polished product moments.",
    itemCount: 14,
    updatedAt: "2 hours ago",
    colors: ["#243f3a", "#b7d8c7", "#dbcbb4"],
  },
  {
    id: "customer-voice",
    name: "Customer voice",
    description: "Clear, credible quotes for sales and social.",
    itemCount: 9,
    updatedAt: "Yesterday",
    colors: ["#70524a", "#d7c4b4", "#f0e8dd"],
  },
  {
    id: "founder-led",
    name: "Founder-led ideas",
    description: "Hooks, observations, and brand-story building blocks.",
    itemCount: 21,
    updatedAt: "Jul 23",
    colors: ["#314b50", "#8aa3a1", "#d4ddd8"],
  },
];

export const teamMembers = [
  { id: 1, name: "Alex Morgan", email: "alex@northstar.studio", role: "Owner", initials: "AM" },
  { id: 2, name: "Daniel Giraldo", email: "daniel@northstar.studio", role: "Admin", initials: "DG" },
  { id: 3, name: "Priya Shah", email: "priya@northstar.studio", role: "Member", initials: "PS" },
];
